### ISSUE TITLE
topeka crashs 

### ISSUE THREAD

**Issue by MontassarWCT** [googlesamples/android-topeka#16]
06-18 16:29:26.778  29605-29605/com.google.samples.apps.topeka W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41cecc08)
06-18 16:29:26.778  29605-29605/com.google.samples.apps.topeka E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.google.samples.apps.topeka, PID: 29605
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.samples.apps.topeka/com.google.samples.apps.topeka.activity.SignInActivity}: android.view.InflateException: Binary XML file line #17: Error inflating class com.google.samples.apps.topeka.widget.fab.DoneFab
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
            at android.app.ActivityThread.access$900(ActivityThread.java:175)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5603)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.google.samples.apps.topeka.widget.fab.DoneFab
            at android.view.LayoutInflater.createView(LayoutInflater.java:626)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:827)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:751)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at com.google.samples.apps.topeka.fragment.SignInFragment.onCreateView(SignInFragment.java:68)
            at android.app.Fragment.performCreateView(Fragment.java:1700)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.BackStackRecord.run(BackStackRecord.java:684)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
            at android.app.Activity.performStart(Activity.java:5467)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
            at android.app.ActivityThread.access$900(ActivityThread.java:175)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5603)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:600)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:827)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:751)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at com.google.samples.apps.topeka.fragment.SignInFragment.onCreateView(SignInFragment.java:68)
            at android.app.Fragment.performCreateView(Fragment.java:1700)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.BackStackRecord.run(BackStackRecord.java:684)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
            at android.app.Activity.performStart(Activity.java:5467)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
            at android.app.ActivityThread.access$900(ActivityThread.java:175)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5603)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NoClassDefFoundError: com.google.samples.apps.topeka.widget.outlineprovider.FabOutlineProvider
            at com.google.samples.apps.topeka.widget.fab.FloatingActionButton.<init>(FloatingActionButton.java:46)
            at com.google.samples.apps.topeka.widget.fab.DoneFab.<init>(DoneFab.java:34)
            at com.google.samples.apps.topeka.widget.fab.DoneFab.<init>(DoneFab.java:30)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:600)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:827)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:751)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at com.google.samples.apps.topeka.fragment.SignInFragment.onCreateView(SignInFragment.java:68)
            at android.app.Fragment.performCreateView(Fragment.java:1700)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.BackStackRecord.run(BackStackRecord.java:684)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
            at android.app.Activity.performStart(Activity.java:5467)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
            at android.app.ActivityThread.access$900(ActivityThread.java:175)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5603)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by keyboardsurfer** [comment]
Which device and Android version did you use?

**Comment by MontassarWCT** [comment]
I use my Tablette GALAXY Tab Note2(version Android : 4.4.2).

**Comment by keyboardsurfer** [comment]
The minSdkVersion for Topeka is 21. Android 4.4.2 is SDK version 19.

**Comment by VishalThareja** [comment]
not being able to run application on phone version from android 4.0 after being setting minimum sdk to 17

**Comment by keyboardsurfer** [comment]
The currently released state of the app is not designed to run on API levels lower than 21.
This is working as intended.

**Comment by IgorGanapolsky** [comment]
So there is no solution to this dilemma?

**Comment by tjohns** [comment]
@IgorGanapolsky Not directly. You can implement Material Design on older devices by using the [Android Design Support Library][1] in your own apps, but this app does not use that. Accordingly, you must have a device running Android 5.0 or later to run this.

[1]: http://android-developers.blogspot.com/2015/05/android-design-support-library.html

**Comment by IgorGanapolsky** [comment]
@tjohns Thanks for the effort and nice sample anyhow.  @changetip $1.

**Comment by changetip** [comment]
Hi @tjohns, @IgorGanapolsky sent you a tip worth 4,183 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/900977)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by tjohns** [comment]
@IgorGanapolsky Thanks! That probably should go to @keyboardsurfer, but I'll make sure it finds its way to him.
