### ISSUE TITLE
Sometimes crash on back press from test

### ISSUE THREAD

**Issue by akadatsky** [googlesamples/android-topeka#5]
Device: Nexus 4
Android version: 5.1.1

06-17 10:35:06.099  10078-10078/com.google.samples.apps.topeka E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.google.samples.apps.topeka, PID: 10078
    java.lang.NullPointerException: Attempt to read from field 'android.os.Handler android.app.Activity.mHandler' on a null object reference
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1427)
            at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:483)
            at android.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:498)
            at android.app.Activity.onBackPressed(Activity.java:2482)
            at com.google.samples.apps.topeka.activity.QuizActivity.access$201(QuizActivity.java:42)
            at com.google.samples.apps.topeka.activity.QuizActivity$2.onAnimationEnd(QuizActivity.java:127)
            at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1116)
            at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1171)
            at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:722)
            at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:738)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:549)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by partha3028** [comment]
What is the solution to the above problem?
