### ISSUE TITLE
FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by tlvprasad** [googlesamples/android-topeka#62]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.google.samples.apps.topeka, PID: 26114
                                                                                java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
                                                                                    at com.google.samples.apps.topeka.helper.PreferencesHelper.writeToPreferences(PreferencesHelper.java:49)
                                                                                    at com.google.samples.apps.topeka.fragment.SignInFragment.savePlayer(SignInFragment.java:238)
                                                                                    at com.google.samples.apps.topeka.fragment.SignInFragment.access$200(SignInFragment.java:48)
                                                                                    at com.google.samples.apps.topeka.fragment.SignInFragment$3.onClick(SignInFragment.java:161)
                                                                                    at android.view.View.performClick(View.java:4820)
                                                                                    at android.view.View$PerformClick.run(View.java:20157)
                                                                                    at android.os.Handler.handleCallback(Handler.java:815)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                    at android.os.Looper.loop(Looper.java:194)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5576)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by keyboardsurfer** [comment]
Fixed in #59.
