### ISSUE TITLE
SignInFragment (gridView.getChildat) can return incorrect views or produce a NPE

### ISSUE THREAD

**Issue by ardock** [googlesamples/android-topeka#64]
The child views are recycled and not all are visible when using a gridView.

To reproduce a NPE, select the last avatar, rotate to landscape mode and press the fab button.
The childCount will be (using a nexus 5) 11 and the avatar.ordinal 16.

The issue is in [this line](https://github.com/googlesamples/android-topeka/blob/master/app/src/main/java/com/google/samples/apps/topeka/fragment/SignInFragment.java#L166) and a better explanation and solution [here](http://stackoverflow.com/questions/26962965) and [here](http://stackoverflow.com/questions/5976533).

```
java.lang.IllegalArgumentException: Shared element must not be null
  at android.app.ActivityOptions.makeSceneTransitionAnimation(ActivityOptions.java:561)
  at android.support.v4.app.ActivityOptionsCompat21.makeSceneTransitionAnimation(ActivityOptionsCompat21.java:45)
  at android.support.v4.app.ActivityOptionsCompat.makeSceneTransitionAnimation(ActivityOptionsCompat.java:171)
  at com.google.samples.apps.topeka.fragment.SignInFragment.performSignInWithTransition(SignInFragment.java:224)
  at com.google.samples.apps.topeka.fragment.SignInFragment.access$800(SignInFragment.java:48)
  at com.google.samples.apps.topeka.fragment.SignInFragment$3$1.run(SignInFragment.java:172)
  at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1119)
  at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
  at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
  at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
  at android.view.Choreographer.doFrame(Choreographer.java:603)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
  11-30 13:26:37.409 28287-28287/com.google.samples.apps.topeka I/Process: Sending signal. PID: 28287 SIG: 9
```

**Comment by ardock** [comment]
@keyboardsurfer It's better that you fix this, I don't know what you expect in this case.

**Comment by piotrek1543** [comment]
@ardock does problem occurs in the latest version?

**Comment by ardock** [comment]
@piotrek1543 I don't remember, closing this by now
